name: CI


on : [ push ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: "adobt"

       - name: clean build
      run: ./gradlew clean test --info --stacktrace
